import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";

const roboto = Roboto_Serif({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={roboto.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
